# Generated by Django 5.0.6 on 2024-06-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('year', models.CharField(max_length=100)),
                ('diretor', models.CharField(max_length=80)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField(blank=True)),
                ('genre', models.CharField(max_length=77)),
                ('age', models.IntegerField(default=0)),
                ('time', models.TimeField()),
                ('producer', models.CharField(max_length=70)),
                ('operator', models.CharField(max_length=75)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
